### ISSUE TITLE
Typo causing bug (v1.16)

### ISSUE THREAD

**Issue by nop990** [RaidingForPants/hd2-audio-modder#46]
Trying to export a quick test patch but I get an error in the console:

``` plaintext
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1921, in __call__
  File "audio_modder.py", line 4545, in write_patch
  File "audio_modder.py", line 2175, in write_patch
  File "audio_modder.py", line 1364, in rebuild_headers
  File "audio_modder.py", line 1028, in generate
NameError: name 'sources' is not defined
```

Looks like on line 1028 of audio_modder.py it has ```sources.source_id``` when it should have ```source.source_id```

**Comment by RaidingForPants** [comment]
I cry
:'(

Fixed in latest commit, about to make release.
